### ISSUE TITLE
AGPS broken, live display not working

### ISSUE THREAD

**Issue by Immortalin** [kyasu/android_device_samsung_ks01ltexx#2]
AGPS unable to get fix, a quick Google suggests that it's a problem with the newer CM libs and that switching back to old ones may fix the issue. Livedisplay is also not working, stuck at `off`

**Comment by kyasu** [comment]
Thanks for reporting.
AGPS works for me (get fix just few seconds).
LiveDisplay is now fixed.

**Comment by Immortalin** [comment]
@kyasu I received a notification today from the updater about new nightly updates, are those updates from you or CM servers?

**Comment by kyasu** [comment]
I don't know your notification.
I uploaded my build. See  http://forum.xda-developers.com/galaxy-s4/i9506-develop/rom-cyanogenmod-13-0-12-1-unofficial-t3264134

**Comment by Immortalin** [comment]
@kyasu  this is what I mean: [
![screenshot_20160820-145739](https://cloud.githubusercontent.com/assets/7126128/17829659/9494fb26-66e8-11e6-982d-6c2b54c306be.png)
](url)
